import React from 'react';
import { useParams } from 'react-router-dom';
import { Box, Typography, CircularProgress, Paper, Button } from '@mui/material';
import { Download, Print } from '@mui/icons-material';
import { useDispatch, useSelector } from 'react-redux';
import { getMedicalReport } from '../../redux/slices/medicalReportSlice';
import PDFViewer from './PDFViewer';

const MedicalReportViewer = () => {
  const { id } = useParams();
  const dispatch = useDispatch();
  const { currentReport, loading, error } = useSelector((state) => state.medicalReport);

  React.useEffect(() => {
    if (id) {
      dispatch(getMedicalReport(id));
    }
  }, [dispatch, id]);

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', p: 4 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: 3 }}>
        <Typography color="error">{error}</Typography>
      </Box>
    );
  }

  if (!currentReport) {
    return (
      <Box sx={{ p: 3 }}>
        <Typography>Report not found</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 3 }}>
        <Typography variant="h4">
          {currentReport.title}
        </Typography>
        <Box>
          <Button
            variant="contained"
            startIcon={<Download />}
            href={`/api/medical-reports/${currentReport._id}/file`}
            download
            sx={{ mr: 2 }}
          >
            Download
          </Button>
          <Button
            variant="outlined"
            startIcon={<Print />}
            onClick={() => window.print()}
          >
            Print
          </Button>
        </Box>
      </Box>

      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h6" gutterBottom>Report Details</Typography>
        <Typography><strong>Patient:</strong> {currentReport.patient?.fullName || 'N/A'}</Typography>
        <Typography><strong>Generated By:</strong> {currentReport.generatedBy?.firstName} {currentReport.generatedBy?.lastName}</Typography>
        <Typography><strong>Date:</strong> {new Date(currentReport.createdAt).toLocaleDateString()}</Typography>
      </Paper>

      {currentReport.filePath && (
        <Paper sx={{ p: 3 }}>
          <PDFViewer 
            url={`/api/medical-reports/${currentReport._id}/file`} 
            height="800px"
          />
        </Paper>
      )}
    </Box>
  );
};

export default MedicalReportViewer;